import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next JS Tutorial - DigitalPool",
    template: "%s | DigitalPool",
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor: 'lightblue',
          padding: '1rem',
          textAlign: 'center',
        }}>
          <h1>
            Header
          </h1>
        </header>
        {children}
          <footer 
          style={{
            backgroundColor: 'ghostwhite',  
            padding: '1rem',
            textAlign: 'center',
          }}>
            <p>Footer</p>
          </footer>
        </body>
    </html>
  )
}

// {children} is the main content area where other parts of the pages are rendered